mp3Player.setVolume(30)
mp3Player.setEQ(mp3Player.EQ.Jazz)
serial.writeString(mp3Player.getInfo())
serial.writeLine("...")
basic.pause(3000)
serial.writeLine("Play file 1 in 3s by Delay")
mp3Player.playFile(1)
basic.pause(3000)
serial.writeLine("Play file 2 in 3s")
mp3Player.playFileInTime(2, 3)
serial.writeLine("Play file 3 in 5s")
mp3Player.playFileInTime(3, 5)
serial.writeLine("Play file 10 in 10s")
mp3Player.playFileInTime(10, 10)
serial.writeLine("Play file 100 until done")
mp3Player.playFileUntilDone(100)
basic.forever(function () {
    serial.writeLine("Play Next")
    mp3Player.playUntilDone(mp3Player.PlayWhat.Next)
})
